tasks:
  - init: pip install -r ./dev_requirements.txt
  - init: pip install -r ./requirements.txt

vscode:
  extensions:
    - chiragpat.tomorrow-and-tomorrow-night-operator-mono-theme@0.0.6:8LloW7cROkiIHcX7odjBlg==
